import { StyleSheet } from 'react-native';
import { ThemeColors } from '../contexts/ThemeContext';

export const makeStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      backgroundColor: colors.headerBg,
      paddingTop: 60,
      paddingBottom: 16,
      paddingHorizontal: 20,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: { paddingVertical: 4, paddingRight: 12 },
    backButtonText: { fontSize: 16, color: colors.primary, fontWeight: '600' },
    headerTitle: { fontSize: 20, fontWeight: 'bold', color: colors.text },
    headerSpacer: { width: 60 },
    tabContainer: {
      flexDirection: 'row',
      backgroundColor: colors.headerBg,
      paddingHorizontal: 16,
      paddingVertical: 12,
      gap: 8,
    },
    tab: { flex: 1, paddingVertical: 10, borderRadius: 10, backgroundColor: colors.tabInactiveBg, alignItems: 'center' },
    tabActive: { backgroundColor: colors.success },
    tabUpcoming: { backgroundColor: colors.primary },
    tabPast: { backgroundColor: '#8e8e93' },
    tabText: { fontSize: 13, fontWeight: '600', color: colors.tabInactiveText },
    tabTextActive: { color: '#fff' },
    scrollView: { flex: 1 },
    emptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 60, paddingHorizontal: 40 },
    emptyIcon: { fontSize: 48, marginBottom: 12 },
    emptyText: { fontSize: 16, color: colors.textMuted, textAlign: 'center' },
    medicationCard: { backgroundColor: colors.card, marginHorizontal: 16, marginTop: 12, borderRadius: 12, padding: 16 },
    medicationInfo: { marginBottom: 12 },
    medicationName: { fontSize: 18, fontWeight: '700', color: colors.text, marginBottom: 4 },
    medicationDosage: { fontSize: 15, color: colors.textSecondary, marginBottom: 6 },
    medicationDates: { fontSize: 13, color: colors.textMuted, marginBottom: 8 },
    timesRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    timeChip: { backgroundColor: colors.chipBg, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
    timeChipText: { fontSize: 13, color: colors.text, fontWeight: '500' },
    cardActions: { flexDirection: 'row', gap: 8, justifyContent: 'flex-end' },
    editButton: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, backgroundColor: colors.primary },
    editButtonText: { color: '#fff', fontSize: 14, fontWeight: '600' },
    deleteButton: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, backgroundColor: colors.danger },
    deleteButtonText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  });
