import { StyleSheet } from 'react-native';
import { ThemeColors } from '../contexts/ThemeContext';

export const makeStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      backgroundColor: colors.headerBg,
      paddingTop: 60,
      paddingBottom: 16,
      paddingHorizontal: 20,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: { paddingVertical: 4, paddingRight: 12 },
    backButtonText: { fontSize: 16, color: colors.primary, fontWeight: '600' },
    headerTitle: { fontSize: 20, fontWeight: 'bold', color: colors.text },
    headerSpacer: { width: 60 },
    monthNav: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 14,
      backgroundColor: colors.card,
    },
    navButton: { padding: 8 },
    navButtonText: { fontSize: 18, color: colors.primary, fontWeight: '600' },
    monthTitle: { fontSize: 18, fontWeight: '700', color: colors.text },
    dayHeaders: {
      flexDirection: 'row',
      backgroundColor: colors.card,
      paddingBottom: 8,
      paddingHorizontal: 8,
    },
    dayHeaderText: {
      flex: 1,
      textAlign: 'center',
      fontSize: 12,
      fontWeight: '600',
      color: colors.textMuted,
    },
    calendarGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      backgroundColor: colors.card,
      paddingHorizontal: 8,
      paddingBottom: 12,
    },
    dayCell: {
      width: '14.28%',
      aspectRatio: 1,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    dayCellToday: { backgroundColor: colors.chipBg, borderRadius: 20 },
    dayCellSelected: { backgroundColor: colors.primary, borderRadius: 20 },
    dayText: { fontSize: 15, color: colors.text, fontWeight: '500' },
    dayTextToday: { fontWeight: '800' },
    dayTextSelected: { color: '#fff', fontWeight: '700' },
    dot: { width: 6, height: 6, borderRadius: 3, position: 'absolute', bottom: 4 },
    legend: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 20,
      paddingVertical: 10,
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    legendItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    legendDot: { width: 8, height: 8, borderRadius: 4 },
    legendText: { fontSize: 12, color: colors.textSecondary },
    detailScroll: { flex: 1, paddingHorizontal: 16, paddingTop: 12 },
    detailTitle: { fontSize: 16, fontWeight: '700', color: colors.text, marginBottom: 12 },
    doseRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.card,
      padding: 14,
      borderRadius: 10,
      marginBottom: 8,
    },
    doseRowTaken: { backgroundColor: colors.doseCardTakenBg },
    doseLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    doseCheck: { fontSize: 20, fontWeight: 'bold' },
    doseName: { fontSize: 15, fontWeight: '600', color: colors.text },
    doseDosage: { fontSize: 13, color: colors.textSecondary },
    doseTime: { fontSize: 14, fontWeight: '600', color: colors.textSecondary },
    noDataText: { textAlign: 'center', color: colors.textMuted, fontSize: 15, marginTop: 30 },
  });
