import { StyleSheet, Dimensions } from 'react-native';
import { ThemeColors } from '../contexts/ThemeContext';

export const SCREEN_WIDTH = Dimensions.get('window').width;
export const DRAWER_WIDTH = SCREEN_WIDTH * 0.75;

export const makeStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      backgroundColor: colors.headerBg,
      paddingTop: 60,
      paddingBottom: 16,
      paddingHorizontal: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    menuButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.chipBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    menuIcon: { fontSize: 22, color: colors.text },
    headerTitle: { fontSize: 22, fontWeight: 'bold', color: colors.text },
    headerRight: { flexDirection: 'row', gap: 8 },
    allButton: {
      backgroundColor: 'transparent',
      borderWidth: 1,
      borderColor: colors.primary,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 18,
    },
    allButtonText: { color: colors.primary, fontSize: 14, fontWeight: '600' },
    addButton: {
      backgroundColor: colors.primary,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 18,
    },
    addButtonText: { color: '#fff', fontSize: 14, fontWeight: '600' },

    overlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.45)',
      zIndex: 10,
    },

    drawer: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      width: DRAWER_WIDTH,
      backgroundColor: colors.card,
      zIndex: 20,
      shadowColor: '#000',
      shadowOffset: { width: 4, height: 0 },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 16,
    },
    drawerHeader: {
      backgroundColor: colors.primary,
      paddingTop: 70,
      paddingBottom: 24,
      paddingHorizontal: 24,
    },
    drawerAppName: { fontSize: 22, fontWeight: '800', color: '#fff', marginBottom: 12 },
    drawerDateDay: { fontSize: 18, fontWeight: '600', color: 'rgba(255,255,255,0.9)' },
    drawerDateFull: { fontSize: 14, color: 'rgba(255,255,255,0.7)', marginTop: 2 },
    drawerStatsRow: { marginTop: 12 },
    drawerStatsBadge: {
      backgroundColor: 'rgba(255,255,255,0.2)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 12,
      alignSelf: 'flex-start',
    },
    drawerStatsText: { fontSize: 13, color: '#fff', fontWeight: '600' },
    drawerBody: { flex: 1, paddingTop: 8 },
    drawerSectionLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textMuted,
      letterSpacing: 1,
      paddingHorizontal: 24,
      paddingTop: 16,
      paddingBottom: 8,
    },
    drawerItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingVertical: 14,
      gap: 14,
    },
    drawerItemIcon: { fontSize: 20 },
    drawerItemText: { fontSize: 16, color: colors.text, fontWeight: '500' },
    drawerDivider: { height: 1, backgroundColor: colors.border, marginHorizontal: 24, marginVertical: 4 },
    drawerFooter: { paddingHorizontal: 24, paddingVertical: 20 },
    drawerFooterText: { fontSize: 12, color: colors.textMuted },

    progressContainer: { backgroundColor: colors.card, padding: 20, marginTop: 1 },
    progressText: { fontSize: 16, fontWeight: '600', color: colors.text, marginBottom: 10 },
    progressBar: { height: 8, backgroundColor: colors.progressBg, borderRadius: 4, overflow: 'hidden' },
    progressFill: { height: '100%', backgroundColor: colors.success, borderRadius: 4 },

    scrollView: { flex: 1 },

    emptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 80, paddingHorizontal: 40 },
    emptyIcon: { fontSize: 64, marginBottom: 16 },
    emptyTitle: { fontSize: 20, fontWeight: 'bold', color: colors.text, marginBottom: 8 },
    emptyText: { fontSize: 16, color: colors.textSecondary, textAlign: 'center' },

    doseCard: {
      backgroundColor: colors.card,
      marginHorizontal: 16,
      marginTop: 12,
      borderRadius: 12,
      padding: 16,
      borderWidth: 2,
      borderColor: colors.doseCardBorder,
    },
    doseCardTaken: { backgroundColor: colors.doseCardTakenBg, borderColor: colors.doseCardTakenBorder },
    doseMain: { flexDirection: 'row', alignItems: 'center' },
    checkbox: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    checkmark: { fontSize: 18, color: colors.success, fontWeight: 'bold' },
    doseInfo: { flex: 1 },
    doseName: { fontSize: 18, fontWeight: '600', color: colors.text, marginBottom: 4 },
    doseNameTaken: { color: colors.textMuted },
    doseDosage: { fontSize: 14, color: colors.textSecondary },
    doseTimeContainer: { alignItems: 'flex-end' },
    doseTime: { fontSize: 16, fontWeight: '600', color: colors.textSecondary },
    doseTimeUpcoming: { color: colors.primary },

    medicationsSection: { marginTop: 24, marginBottom: 24, paddingHorizontal: 16 },
    sectionTitle: { fontSize: 18, fontWeight: 'bold', color: colors.text, marginBottom: 12 },
    medicationCard: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    medicationInfo: { flex: 1 },
    medicationName: { fontSize: 16, fontWeight: '600', color: colors.text, marginBottom: 4 },
    medicationDetails: { fontSize: 14, color: colors.textSecondary, marginBottom: 4 },
    medicationDates: { fontSize: 12, color: colors.textMuted },
    cardActions: { flexDirection: 'row', gap: 8 },
    editButton: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, backgroundColor: colors.primary },
    editButtonText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  });
