import { StyleSheet } from 'react-native';
import { ThemeColors } from '../contexts/ThemeContext';

export const makeStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    content: { padding: 20, paddingTop: 60 },
    title: { fontSize: 28, fontWeight: 'bold', marginBottom: 30, color: colors.text },
    inputGroup: { marginBottom: 24 },
    label: { fontSize: 16, fontWeight: '600', marginBottom: 8, color: colors.text },
    input: {
      backgroundColor: colors.inputBg,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 12,
      padding: 16,
      fontSize: 16,
      color: colors.text,
    },
    dateButton: {
      backgroundColor: colors.inputBg,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 12,
      padding: 16,
    },
    dateButtonText: { fontSize: 16, color: colors.text },
    addTimeButton: {
      backgroundColor: colors.primary,
      borderRadius: 12,
      padding: 16,
      alignItems: 'center',
      marginBottom: 12,
    },
    addTimeButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
    timeChip: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.inputBg,
      borderRadius: 8,
      padding: 12,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    timeChipText: { fontSize: 16, color: colors.text },
    removeButton: { fontSize: 20, color: colors.danger, fontWeight: 'bold' },
    timePickerButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    cancelTimeText: { fontSize: 16, color: colors.textSecondary, padding: 10 },
    confirmTimeText: { fontSize: 16, color: colors.primary, fontWeight: '600', padding: 10 },
    buttonGroup: { flexDirection: 'row', gap: 12, marginTop: 30, marginBottom: 40 },
    cancelButton: {
      flex: 1,
      padding: 18,
      borderRadius: 12,
      alignItems: 'center',
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    cancelButtonText: { fontSize: 16, fontWeight: '600', color: colors.text },
    saveButton: {
      flex: 1,
      padding: 18,
      borderRadius: 12,
      alignItems: 'center',
      backgroundColor: colors.success,
    },
    saveButtonBlue: {
      flex: 1,
      padding: 18,
      borderRadius: 12,
      alignItems: 'center',
      backgroundColor: colors.primary,
    },
    saveButtonText: { fontSize: 16, fontWeight: '600', color: '#fff' },
  });
